name: Python application CI

"on":
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.10.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.11

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Install dependencies
        run: |
          uv venv
          uv sync

      - name: Install pre-commit
        run: |
          source .venv/bin/activate
          pip install pre-commit

      - name: Run pre-commit
        run: |
          source .venv/bin/activate
          pre-commit run --all-files

      - name: Run tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          source .venv/bin/activate
          pytest
